[package]
name = "gas_calibration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
massa-sc-runtime = { git = "https://github.com/massalabs/massa-sc-runtime", tag = "v0.8.2" }
massa-models = { git = "https://github.com/massalabs/massa", package = "massa_models", tag = "TEST.16.0" }
massa-signature = { git = "https://github.com/massalabs/massa", package = "massa_signature", tag = "TEST.16.0" }
rand = "0.8.5"