[package]
name = "gas_calibration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
pbr = { git = "https://github.com/a8m/pb" }
massa-sc-runtime = { git = "https://github.com/massalabs/massa-sc-runtime", tag = "v0.8.2" }
massa-models = { git = "https://github.com/massalabs/massa", package = "massa_models", branch = "gas_calibration" }
massa-signature = { git = "https://github.com/massalabs/massa", package = "massa_signature", branch = "gas_calibration" }
massa-execution-worker = { git = "https://github.com/massalabs/massa", package = "massa_execution_worker", branch = "gas_calibration", features = ["gas_calibration"] }
rand = "0.8.5"